first_step = input("Please choose integer number from 1 to 3 ")
if int(first_step) == 1:
    template_1_1 = input("input Number(Measure of time)")
    template_1_2 = input("input Made of Transportation")
    template_1_3 = input("input Adjective")
    template_1_4 = input("input Adjective(Noun)")
    template_1_5 = input("input Color(Part of the Body)")
    template_1_6 = input("input Verb")
    template_1_7 = input("input Number(Noun)")
    template_1_8 = input("input Noun")
    template_1_9 = input("input Part of the Body")
    template_1_10 = input("input Verb(Noun)")
    template_1_11 = input("input Adjective")
    template_1_12 = input("input Silly Word(Noun)")
    print(f"It was about {template_1_1} ago when I arrived at the hospital in a {template_1_2}. The hospital")
    print(f"is a/an {template_1_3} place, there are a lot of {template_1_4} here. There are nurses")
    print(f"here who have {template_1_5}. If someone wants to come into my room I told them that they")
    print(f"have to {template_1_6}. Today I taked to a doctor and they were wearing a {template_1_8} on")
    print(f"their {template_1_9}. I heard that all doctors {template_1_10} every day for breakfast.")
    print(f"The most {template_1_11} thing about being in the hospital is the {template_1_12}")
elif int(first_step) == 2:
    template_2_1 = input("input Proper Noun(Person's name)")
    template_2_2 = input("input Noun")
    template_2_3 = input("input Adjective(Feeling)")
    template_2_4 = input("input Verb")
    template_2_5 = input("input Adjective(Feeling)")
    template_2_6 = input("input Animal")
    template_2_7 = input("input Verb")
    template_2_8 = input("input Color")
    template_2_9 = input("input Verb(ending in ing)")
    template_2_10 = input("input Adverb(ending in ly)")
    template_2_11 = input("input Number(Measure of Time)")
    template_2_12 = input("input Color(Animal)")
    template_2_13 = input("input Number(Silly Word)")
    template_2_14 = input("input Noun")
    print(f"This weekend I am going camping with {template_2_1}. I picked my lantern, sleeping")
    print(f"bag and {template_2_2}. I am so {template_2_3} to {template_2_4} in a tent. I am")
    print(f"{template_2_5}  we might see a(n) {template_2_6}. I have heard they`re kind of")
    print(f"dangerous. While we are camping we are going to hike, fish and {template_2_7}.")
    print(f"I have heard that the {template_2_8} is great for {template_2_9}. Then we will")
    print(f"{template_2_10} hike through the  forest for {template_2_11} If I see a {template_2_12}")
    print(f"while hiking I am going to bring it home as a pet! At night we will tell")
    print(f"{template_2_13} stories and roast {template_2_14} around the campfire!!")
elif int(first_step) == 3:
    template_3_1 = input("input Proper Noun(Person's name)")
    template_3_2 = input("input Adjective")
    template_3_3 = input("input Color(Animal)")
    template_3_4 = input("input Place")
    template_3_5 = input("input Adjective(Magical Creature(Plural))")
    template_3_6 = input("input Adjective(Magical Creature(Plural))")
    template_3_7 = input("input Noun")
    template_3_8 = input("input Noun")
    template_3_9 = input("input Noun(Plural))")
    template_3_10 = input("input Adjective(Noun(Plural))")
    template_3_11 = input("input Number(Measure of time)")
    template_3_12 = input("input Verb(ending in ing)")
    template_3_13 = input("input Adjective(Noun)")
    print(f"Dear {template_3_1} I am writing to you from  a {template_3_2} castle in an enchanted forest.")
    print(f"I found myself here one day after going for a ride on a {template_3_3} in {template_3_4}.")
    print(f"There are {template_3_5} and {template_3_6} here! In the (Room in the house) there is a pool ")
    print(f"full of {template_3_7}.I fall asleep each night on a {template_3_8} of {template_3_9} and ")
    print(f"dream of  {template_3_10}. It feels as though I have lived for {template_3_11}. I hope one day")
    print(f"you can visit, although the only way to get here now is {template_3_12} on a {template_3_13}.")
else:
    print("please input integer number in the range of 1 and 3")


