first_step = input("please choose integer number from 1 to 3 \n ")
if int(first_step) == 1:
    templet_1_1 = input("input number meger of time ")
    templet_1_2 = input("input Made of Transportation ")
    templet_1_3 = input("input Adjactive ")
    templet_1_4 = input("input Adjactive (Noun) ")
    templet_1_5 = input("input Color (Part of the Body) ")
    templet_1_6 = input("input Verb ")
    templet_1_7 = input("input Number(Noun) ")
    templet_1_8 = input("input Noun ")
    templet_1_9 = input("input Part of the Body ")
    templet_1_10 = input("input Verb(Noun) ")
    templet_1_11 = input("input Adjactive")
    templet_1_12 = input("input Silly Word (Noun) ")
    print(f"It was about {templet_1_1} ago when I arrived at the hospital in a {templet_1_2}. The hospital")
    print(f"is a/an {templet_1_3} noise place, ther are a lot of {templet_1_4} here. Tere are nueses")
    print(f"here who have {templet_1_5}. If someone wants to come into my room I told them that they")
    print(f"have to {templet_1_6}. Today I taked to a doctor and they were wearing a {templet_1_8} on")
    print(f"their {templet_1_9}. I heard that all doctors {templet_1_10} every day for breakfast.")
    print(f"The most {templet_1_11} thing about being in hospital is the {templet_1_12}")
elif int(first_step) == 2:
    templet_2_1 = input("input Proper Noun(Person`s name) ")
    templet_2_2 = input("input Noun ")
    templet_2_3 = input("input Adjective(feeling) ")
    templet_2_4 = input("input Verb ")
    templet_2_5 = input("input Adjective(feeling) ")
    templet_2_6 = input("input Animal ")
    templet_2_7 = input("input Verb ")
    templet_2_8 = input("input Color ")
    templet_2_9 = input("input Verb(ending in ing) ")
    templet_2_10 = input("input Adverb(ending in ly) ")
    templet_2_11 = input("input Number(Measure of Time) ")
    templet_2_12 = input("input Color(Animal) ")
    templet_2_13 = input("input Number(Silly Word) ")
    templet_2_14 = input("input Noun ")
    print(f"This weekend I am going camping with {templet_2_1}. I picked my lantern, sleeping")
    print(f"bag and {templet_2_2}. I am so {templet_2_3} to {templet_2_4} in a tent. I am")
    print(f"{templet_2_5}  we might see a(n) {templet_2_6}. I have heard they`re kind of")
    print(f"dangerous. While we are camping we are going to hike, fish and {templet_2_7}.")
    print(f"I have heard that the {templet_2_8} is great for {templet_2_9}. Then we will")
    print(f"{templet_2_10} hike through the  forest for {templet_2_11} If I see a {templet_2_12}")
    print(f"while hiking I am going to bring it home as a pet! At night we will tell")
    print(f"{templet_2_13} stories and roast {templet_2_14} around the campfire!!")
elif int(first_step) == 3:
    templet_3_1 = input("input Proper Noun(Person`s name) ")
    templet_3_2 = input("input Adjective ")
    templet_3_3 = input("input Color(Animal) ")
    templet_3_4 = input("input Place ")
    templet_3_5 = input("input Adjective(Megical Creature(Plural)) ")
    templet_3_6 = input("input Adjective(Megical Creature(Plural)) ")
    templet_3_7 = input("input Noun ")
    templet_3_8 = input("input Noun ")
    templet_3_9 = input("input Noun(Plural)) ")
    templet_3_10 = input("input Adjective(Noun(Plural)) ")
    templet_3_11 = input("input number (meger of time) ")
    templet_3_12 = input("input Verb ()ending in ing ")
    templet_3_13 = input("input Adjective(Noun) ")
    print(f"Dear {templet_3_1} I am writing to you from  a {templet_3_2} castle in an enchanted forest.")
    print(f"I found myself here one day after going for a ride on a {templet_3_3} in {templet_3_4}.")
    print(f"There are {templet_3_5} and {templet_3_6} here! In the (Room in the house) there is a pool ")
    print(f"full of {templet_3_7}.I fall asleep each night on a {templet_3_8} of {templet_3_9} and ")
    print(f"dream of  {templet_3_10}. It feels as though I have lived for {templet_3_11}. I hope one day")
    print(f"you can visit, although the only way to get here now is {templet_3_12} on a {templet_3_13}.")
else:
    print("please input integer number in the range of 1 and 3 ")


